### ISSUE TITLE
gasket-dkms not work on 6.17.9+deb14-arm64 (aarch64)

### ISSUE THREAD

**Issue by electro575** [google-coral/edgetpu#911]
Hi all,

I'm working on debian sid 6.17.9+deb14-arm64 (aarch64) and want to use a google coral SATA M.2.

Here is the log.
cat /var/lib/dkms/gasket/1.0/build/make.log

```
DKMS (dkms-3.2.2) make.log for gasket/1.0 for kernel 6.17.9+deb14-arm64 (aarch64)
dim. 30 nov. 2025 15:18:19 CET

Building module(s)
# command: make -j4 KERNELRELEASE=6.17.9+deb14-arm64 -C /lib/modules/6.17.9+deb14-arm64/build M=/var/lib/dkms/gasket/1.0/build
make : on entre dans le répertoire « /usr/src/linux-headers-6.17.9+deb14-arm64 »
make[1] : on entre dans le répertoire « /var/lib/dkms/gasket/1.0/build »
  CC [M]  gasket_core.o
  CC [M]  gasket_ioctl.o
  CC [M]  gasket_interrupt.o
  CC [M]  gasket_page_table.o
gasket_interrupt.c: In function ‘gasket_handle_interrupt’:
gasket_interrupt.c:161:17: error: too many arguments to function ‘eventfd_signal’; expected 1, have 2
  161 |                 eventfd_signal(ctx, 1);
      |                 ^~~~~~~~~~~~~~      ~
In file included from gasket_interrupt.h:11,
                 from gasket_interrupt.c:4:
/usr/src/linux-headers-6.17.9+deb14-common/include/linux/eventfd.h:87:20: note: declared here
   87 | static inline void eventfd_signal(struct eventfd_ctx *ctx)
      |                    ^~~~~~~~~~~~~~
gasket_core.c:1375:19: error: ‘no_llseek’ undeclared here (not in a function); did you mean ‘noop_llseek’?
 1375 |         .llseek = no_llseek,
      |                   ^~~~~~~~~
      |                   noop_llseek
make[3]: *** [/usr/src/linux-headers-6.17.9+deb14-common/scripts/Makefile.build:292: gasket_interrupt.o] Error 1
make[3]: *** Attente des tâches non terminées....
gasket_core.c: In function ‘gasket_register_device’:
gasket_core.c:1841:41: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Wincompatible-pointer-types]
 1841 |                 class_create(driver_desc->module, driver_desc->name);
      |                              ~~~~~~~~~~~^~~~~~~~
      |                                         |
      |                                         struct module *
In file included from /usr/src/linux-headers-6.17.9+deb14-common/include/linux/device.h:30,
                 from /usr/src/linux-headers-6.17.9+deb14-common/include/linux/cdev.h:8,
                 from gasket_core.h:11,
                 from gasket_core.c:12:
/usr/src/linux-headers-6.17.9+deb14-common/include/linux/device/class.h:226:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
  226 | struct class * __must_check class_create(const char *name);
      |                                          ~~~~~~~~~~~~^~~~
gasket_core.c:1841:17: error: too many arguments to function ‘class_create’; expected 1, have 2
 1841 |                 class_create(driver_desc->module, driver_desc->name);
      |                 ^~~~~~~~~~~~                      ~~~~~~~~~~~~~~~~~
/usr/src/linux-headers-6.17.9+deb14-common/include/linux/device/class.h:226:29: note: declared here
  226 | struct class * __must_check class_create(const char *name);
      |                             ^~~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-6.17.9+deb14-common/scripts/Makefile.build:292: gasket_core.o] Error 1
In file included from /usr/src/linux-headers-6.17.9+deb14-common/include/linux/module.h:23,
                 from /usr/src/linux-headers-6.17.9+deb14-common/include/linux/device/driver.h:21,
                 from /usr/src/linux-headers-6.17.9+deb14-common/include/linux/device.h:32,
                 from /usr/src/linux-headers-6.17.9+deb14-common/include/linux/pci.h:37,
                 from gasket_page_table.h:15,
                 from gasket_page_table.c:42:
gasket_page_table.c:57:18: error: expected ‘,’ or ‘;’ before ‘DMA_BUF’
   57 | MODULE_IMPORT_NS(DMA_BUF);
      |                  ^~~~~~~
/usr/src/linux-headers-6.17.9+deb14-common/include/linux/moduleparam.h:31:61: note: in definition of macro ‘MODULE_INFO’
   31 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
      |                                                             ^~~~
gasket_page_table.c:57:1: note: in expansion of macro ‘MODULE_IMPORT_NS’
   57 | MODULE_IMPORT_NS(DMA_BUF);
      | ^~~~~~~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-6.17.9+deb14-common/scripts/Makefile.build:292: gasket_page_table.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.17.9+deb14-common/Makefile:2035: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.17.9+deb14-common/Makefile:260: __sub-make] Error 2
make[1] : on quitte le répertoire « /var/lib/dkms/gasket/1.0/build »
make: *** [/usr/src/linux-headers-6.17.9+deb14-common/Makefile:260: __sub-make] Error 2
make : on quitte le répertoire « /usr/src/linux-headers-6.17.9+deb14-arm64 »

# exit code: 2
# elapsed time: 00:00:06
```

Thanks a lot for patches
