### ISSUE TITLE
Building gasket-dkms broken on linux kernel 6.5.0 (Ubuntu 23.10)

### ISSUE THREAD

**Issue by dewet22** [google-coral/edgetpu#808]
### Description

Just upgraded my machines with PCIe TPUs from Ubuntu 23.04 to 23.10, upgrading from kernel 6.2 to 6.5.0.

apt/dpkg output:
```
...
Setting up python3-distupgrade (1:23.10.10) ...
Setting up gasket-dkms (1.0-18) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Removing old gasket-1.0 DKMS files...
Deleting module gasket-1.0 completely from the DKMS tree.
Loading new gasket-1.0 DKMS files...
Deprecated feature: REMAKE_INITRD (/usr/src/gasket-1.0/dkms.conf)
Building for 6.5.0-10-generic
Building initial module for 6.5.0-10-generic
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/gasket/1.0/source/dkms.conf)
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/gasket-dkms.0.crash'
Error! Bad return status for module build on kernel: 6.5.0-10-generic (x86_64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: error processing package gasket-dkms (--configure):
 installed gasket-dkms package post-installation script subprocess returned error exit status 10
Setting up ubuntu-release-upgrader-core (1:23.10.10) ...
Processing triggers for dbus (1.14.10-1ubuntu1) ...
Errors were encountered while processing:
 gasket-dkms
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

The mentioned crash log `/var/crash/gasket-dkms.0.crash`:
```
ProblemType: Package
DKMSBuildLog:
 DKMS make.log for gasket-1.0 for kernel 6.5.0-10-generic (x86_64)
 Thu Nov  9 21:35:37 UTC 2023
 make: Entering directory '/usr/src/linux-headers-6.5.0-10-generic'
 warning: the compiler differs from the one used to build the kernel
   The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.2.0-4ubuntu3) 13.2.0
   You are using:           gcc-13 (Ubuntu 13.2.0-4ubuntu3) 13.2.0
   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
   CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
 /var/lib/dkms/gasket/1.0/build/gasket_core.c: In function ‘gasket_register_device’:
 /var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:41: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  1841 |                 class_create(driver_desc->module, driver_desc->name);
       |                              ~~~~~~~~~~~^~~~~~~~
       |                                         |
       |                                         struct module *
 In file included from ./include/linux/device.h:31,
                  from ./include/linux/cdev.h:8,
                  from /var/lib/dkms/gasket/1.0/build/gasket_core.h:11,
                  from /var/lib/dkms/gasket/1.0/build/gasket_core.c:12:
 ./include/linux/device/class.h:230:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
   230 | struct class * __must_check class_create(const char *name);
       |                                          ~~~~~~~~~~~~^~~~
 /var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:17: error: too many arguments to function ‘class_create’
  1841 |                 class_create(driver_desc->module, driver_desc->name);
       |                 ^~~~~~~~~~~~
 ./include/linux/device/class.h:230:29: note: declared here
   230 | struct class * __must_check class_create(const char *name);
       |                             ^~~~~~~~~~~~
 cc1: some warnings being treated as errors
 make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/gasket/1.0/build/gasket_core.o] Error 1
 make[2]: *** Waiting for unfinished jobs....
 make[1]: *** [/usr/src/linux-headers-6.5.0-10-generic/Makefile:2037: /var/lib/dkms/gasket/1.0/build] Error 2
 make: *** [Makefile:234: __sub-make] Error 2
 make: Leaving directory '/usr/src/linux-headers-6.5.0-10-generic'
DKMSKernelVersion: 6.5.0-10-generic
Date: Thu Nov  9 21:35:39 2023
DuplicateSignature: dkms:gasket-dkms:1.0-18:/var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:41: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
Package: gasket-dkms 1.0-18
PackageVersion: 1.0-18
SourcePackage: gasket-dkms
Title: gasket-dkms 1.0-18: gasket kernel module failed to build
```

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Ubuntu

### Relevant Log Output

_No response_</details>

**Comment by dewet22** [comment]
Previously reported as #695 and #785.

**Comment by dewet22** [comment]
This was fixed a few months ago in https://github.com/google/gasket-driver/ already; for my use case I just built the .deb from that repo directly and deployed across my Coral-bearing machines.

**Comment by arevindh** [comment]
> This was fixed a few months ago in https://github.com/google/gasket-driver/ already; for my use case I just built the .deb from that repo directly and deployed across my Coral-bearing machines.

I am trying to build it for Promox, can you guide me on how to build it ?

**Comment by dewet22** [comment]
> I am trying to build it for Promox, can you guide me on how to build it ?

I don't use or know Proxmox so I can't help directly. If you need help on building a deb from sources, there are plenty of guides on the internet for that and the starting clue is in the linked repo already: `debuild` is the tool you'll need to use.

**Comment by arevindh** [comment]
> > I am trying to build it for Promox, can you guide me on how to build it ?
> 
> I don't use or know Proxmox so I can't help directly. If you need help on building a deb from sources, there are plenty of guides on the internet for that and the starting clue is in the linked repo already: `debuild` is the tool you'll need to use.

Oh ok , when i try `debuild` only thing i get is the below 

`dh: error: unable to load addon dkms: Can't locate Debian/Debhelper/Sequence/dkms.pm in @INC (you may need to install the Debian::Debhelper::Sequence::dkms module) `

`Debian::Debhelper::Sequence::dkms module)` also impossible to install

Did you get any similar errors?

**Comment by dewet22** [comment]
Make sure you have the `dkms` debhelper package installed: `sudo apt install dh-dkms`

**Comment by arevindh** [comment]
> dh-dkms

Oops I didnt install `dh-dkms` , Thank you, let me try building

**Comment by arevindh** [comment]
@dewet22 frigate is working now 👍.

**Comment by alienatedsec** [comment]
> Make sure you have the `dkms` debhelper package installed: `sudo apt install dh-dkms`

Some Proxmox instances require more effort ;)

`sudo apt install dh-dkms devscripts git`

**Comment by arevindh** [comment]
> > Make sure you have the `dkms` debhelper package installed: `sudo apt install dh-dkms`
> 
> Some Proxmox instances require more effort ;)
> 
> `sudo apt install dh-dkms devscripts git`
> 

Yep , I did post in Double take discord server

**Comment by rkbest13** [comment]
I have similar issue and the steps above dont work. 
If I try the debuild command, it returns 
debuild: fatal error at line 679: cannot find readable debian/changlog anywhere!

dh-dkms is installed.

**Comment by Indianb0y016** [comment]
> I have similar issue and the steps above dont work. If I try the debuild command, it returns debuild: fatal error at line 679: cannot find readable debian/changlog anywhere!
> 
> dh-dkms is installed.

Did you make sure you were in the respective directory? Building the gasket-driver should not fail if the necessary prereqs are installed, and you are in the right directory. No changelog error indicates you are not in the right directory.

**Comment by bbccdd** [comment]
FYI Workaround for Proxmox (debian based) systems here: https://forum.proxmox.com/threads/update-error-with-coral-tpu-drivers.136888/#post-608975

**Comment by kub3let** [comment]
When will this be available via `https://packages.cloud.google.com/apt` ? 

 It's been fixed but still not available in stable for over 3 months.

I really not want to install all the dev dependencies on a production node.

**Comment by dgates62** [comment]
> When will this be available via `https://packages.cloud.google.com/apt` ?
> 
> It's been fixed but still not available in stable for over 3 months.
> 
> I really not want to install all the dev dependencies on a production node.

Perhaps you could build the package in a Debian LXC or VM, transfer the compiled Debian package to the host Proxmox machine, and then install to avoid installing dev dependencies on a production node? Hope that helps!

**Comment by drikster80** [comment]
This bug is now appearing in the HWE kernel in Ubuntu 22.04 as well. The "stable" repo isn't seeming very table anymore.

What do we need to do to get it packaged and updated in the Debian stable repo?

If you give me write access to the Google Cloud repos, I'll gladly update it myself.

**Comment by Mikescotland** [comment]
Stopped working here too. How to build the correct package for kernel 6.5?

**Comment by dewet22** [comment]
> Stopped working here too. How to build the correct package for kernel 6.5?

@Mikescotland As documented in the earlier notes:

```
❯ sudo apt install devscripts debhelper dh-dkms -y
...
❯ git clone https://github.com/google/gasket-driver.git
Cloning into 'gasket-driver'...
...
❯ cd gasket-driver; debuild -us -uc -tc -b; cd ..
...
dpkg-deb: building package 'gasket-dkms' in '../gasket-dkms_1.0-18_all.deb'.
...
❯ ls -l gasket-dkms*
-rw-r--r-- 1 dewet dewet 49000 Jan 17 13:17 gasket-dkms_1.0-18_all.deb
-rw-r--r-- 1 dewet dewet  1788 Jan 17 13:18 gasket-dkms_1.0-18_amd64.build
-rw-r--r-- 1 dewet dewet  5642 Jan 17 13:17 gasket-dkms_1.0-18_amd64.buildinfo
-rw-r--r-- 1 dewet dewet  1017 Jan 17 13:17 gasket-dkms_1.0-18_amd64.changes
```

You can install that `.deb` on any systems that need to build the kernel module, and it will be rebuilt automatically with newer kernel packages being installed:

```
❯ sudo dpkg -i gasket-dkms_1.0-18_all.deb
...
Setting up gasket-dkms (1.0-18) ...
...
Building for 6.5.0-14-generic
Building initial module for 6.5.0-14-generic
...
depmod...
Time: 0h:00m:10s
❯ sudo modprobe apex
❯ lsmod | grep apex
apex                   28672  0
gasket                135168  1 apex
```

**Comment by Mikescotland** [comment]
Got it working
frigate.detectors.plugins.edgetpu_tfl INFO    : TPU found

Thanks for your help!

**Comment by themana** [comment]
@dewet22 I'm trying to follow your directions but I get an error when trying to install dh-dkms, any help would be appreciated.

E: Unable to locate package dh-dkms

This is on the Ubuntu VM with the version info below
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

**Comment by alienatedsec** [comment]
@themana 
```
sudo apt update
sudo apt upgrade
sudo apt install devscripts debhelper -y
```

Then clone and the rest

> ```
> ❯ git clone https://github.com/google/gasket-driver.git
> Cloning into 'gasket-driver'...
> ...
> ❯ cd gasket-driver; debuild -us -uc -tc -b; cd ..
> ...
> dpkg-deb: building package 'gasket-dkms' in '../gasket-dkms_1.0-18_all.deb'.
> ...
> ❯ ls -l gasket-dkms*
> -rw-r--r-- 1 dewet dewet 49000 Jan 17 13:17 gasket-dkms_1.0-18_all.deb
> -rw-r--r-- 1 dewet dewet  1788 Jan 17 13:18 gasket-dkms_1.0-18_amd64.build
> -rw-r--r-- 1 dewet dewet  5642 Jan 17 13:17 gasket-dkms_1.0-18_amd64.buildinfo
> -rw-r--r-- 1 dewet dewet  1017 Jan 17 13:17 gasket-dkms_1.0-18_amd64.changes
> ```
> 
> 
>     
>   
> 
> You can install that `.deb` on any systems that need to build the kernel module, and it will be rebuilt automatically with newer kernel packages being installed:
> 
> 
> ```
> ❯ sudo dpkg -i gasket-dkms_1.0-18_all.deb
> ...
> Setting up gasket-dkms (1.0-18) ...
> ...
> Building for 6.5.0-14-generic
> Building initial module for 6.5.0-14-generic
> ...
> depmod...
> Time: 0h:00m:10s
> ❯ sudo modprobe apex
> ❯ lsmod | grep apex
> apex                   28672  0
> gasket                135168  1 apex
> ```

**Comment by themana** [comment]
@alienatedsec That worked perfectly, thank you so much

**Comment by keptin** [comment]
Thank you a ton @dewet22 and @alienatedsec, that did the trick! Very lucky I found this thread after a good deal of hunting. Cheers!

**Comment by kymocode** [comment]
Thanks @alienatedsec and @dewet22 this worked great. 
Not sure why they havent updated to stable though. Sure would make things much easier

**Comment by matthewharrington** [comment]
Just commenting here to say thanks team. I was tearing my hair out with my Coral failing until I found this thread.

**Comment by bobmarley2021** [comment]
Can I just ask @alienatedsec @bbccdd @arevindh if your Proxmox installs are still working with your Coral? 

I have:

1. Built gasket-dkms from source as per above
2. Tried reverting to a previous kernel (eg. 6.2.16-20-pve)

Modules seem loaded:

```
apex                   28672  0
gasket                135168  1 apex
```

No dice...

```
~ # ls /dev/apex*
zsh: no matches found: /dev/apex*
```

I've gone so far as to order another Coral today as I cannot even get this thing recognised and flashed by webcoral now. Starting to suspect a faulty unit.

**Comment by balashov-ia** [comment]
maybe you should check aspm feature in bios. this thing controls power management of pcie. it helped for me

**Comment by alienatedsec** [comment]
> Can I just ask @alienatedsec @bbccdd @arevindh if your Proxmox installs are still working with your Coral?

Sorry for the late response @bobmarley2021 - I don't know why I missed this message - regardless, my proxmox cluster and all three nodes have the latest versions and work just fine. I documented my effort in [this comment](https://github.com/blakeblackshear/frigate/discussions/5448#discussioncomment-8855247) for frigate installation on proxmox with Coral support 

Installing Coral drivers - go to the shell of the host and type the following commands
```
apt update
apt upgrade
apt install pve-headers-$(uname -r)
apt install proxmox-default-headers
apt install dh-dkms devscripts git
git clone  https://github.com/google/gasket-driver
cd gasket-driver
debuild -us -uc -tc -b -d
cd ..
dpkg -i gasket-dkms_1.0-18_all.deb
reboot
```

Once rebooted, ensure the apex_0 device is in /dev/.
```
ls -alh /dev/apex_0 
crw-rw---- 1 root root 120, 0 Mar 20 14:51 /dev/apex_0
```

Any future kernel updates should automatically include gasket-dkms after above steps.

Follow the rest here https://github.com/blakeblackshear/frigate/discussions/5448#discussioncomment-8855247

**Comment by nglessner** [comment]
> > Can I just ask @alienatedsec @bbccdd @arevindh if your Proxmox installs are still working with your Coral?
> 
> Sorry for the late response @bobmarley2021 - I don't know why I missed this message - regardless, my proxmox cluster and all three nodes have the latest versions and work just fine. I documented my effort in [this comment](https://github.com/blakeblackshear/frigate/discussions/5448#discussioncomment-8855247) for frigate installation on proxmox with Coral support
> 
> Installing Coral drivers - go to the shell of the host and type the following commands
> 
> ```
> apt update
> apt upgrade
> apt install pve-headers-$(uname -r)
> apt install proxmox-default-headers
> apt install dh-dkms devscripts git
> git clone  https://github.com/google/gasket-driver
> cd gasket-driver
> debuild -us -uc -tc -b -d
> cd ..
> dpkg -i gasket-dkms_1.0-18_all.deb
> reboot
> ```
> 
> Once rebooted, ensure the apex_0 device is in /dev/.
> 
> ```
> ls -alh /dev/apex_0 
> crw-rw---- 1 root root 120, 0 Mar 20 14:51 /dev/apex_0
> ```
> 
> Any future kernel updates should automatically include gasket-dkms after above steps.
> 
> Follow the rest here [blakeblackshear/frigate#5448 (comment)](https://github.com/blakeblackshear/frigate/discussions/5448#discussioncomment-8855247)

I wish I could say following your directions worked.

I'm on proxmox 8.1.10 kernel 6.5.13-5 using the dual edge PCIe E-key.  As far as I can tell building the gasket driver was successful, however in the end `ls -alh /dev/apex_0` results in `ls: cannot access '/dev/apex_0': No such file or directory`.

running `lspci -nn | grep 089a` does result in 
`03:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]` so I believe the system can see the TPU, but for whatever reason isn't able to run the driver? 

Anyway, I appreciate the help you've given for this setup.

**Comment by alienatedsec** [comment]
Is there any apex? It doesn't have to be apex_0 for dual edge and it's likely you will see only one. @nglessner

**Comment by nglessner** [comment]
@alienatedsec No. Sorry, I should have been more specific. `ls -alh /dev/apex*` also returns `dev/apex_0': No such file or directory`

I wouldn't think this would be the limiting factor, but I am attempting this on a Beelink EQ12 Pro (N305). The only available M.2 slot is the "WiFi" slot that is also CNVi.  I had high hopes when I could see the device in lspci, but now I'm not so sure.

interestingly lspci -k shows the device as:
`03:00.0 System peripheral: Global Unichip Corp. Coral Edge TPU`
`Subsystem: Global Unichip Corp. Coral Edge TPU`
`Kernel driver in use: vfio-pci`
`Kernel modules: apex`

**Comment by alienatedsec** [comment]
@nglessner Did you already set the PCI pass through and added it to the blocklist?

Asking because if you added an apex device to a blocklist, it will not show on the host. 

> The only available M.2 slot is the "WiFi" slot that is also CNVi.

Most of those slots are CNVi, but have only one PCIe lane, which is the limiting factor to recognise only one Coral.

**Comment by bobmarley2021** [comment]
@alienatedsec not a problem - thanks for replying. I have since solved the issue on my end. In my case there was part faulty product and part user error (although the user error wouldn’t have mattered at that point due to the former). 

I am using a USB coral and didn’t realise that apex is only for PCIe coral. The fault I had with my USB device was causing it not to flash firmware on connection. When I first encountered this problem I googled and was barking up the wrong tree following gasket driver instructions. Then I read on some reviews that certain batches of the USB devices go faulty and appear to exhibit this behaviour - the only solution being to RMA. I replaced the unit and now all is well. I pinned an earlier kernel to be safe, reinstalled the USB driver from the official google repo and I have been up and running ever since :-) 🎉

**Comment by nglessner** [comment]
Thank you @alienatedsec ! My issue was that I had added it to the blocklist.  I eventually got it working!

**Comment by johntdavis84** [comment]
> Most of those slots are CNVi, but have only one PCIe lane, which is the limiting factor to recognise only one Coral.

Is it normal for the CNVi slot to not even recognize the Coral?

I've got an HP Elite Mini, and I can't even see the card in lspci in Proxmox.
I can't decide if it's broken, or if something is actually misconfigured in the BIOS.

More likely, it's just not _supported_ in the BIOS.

**Comment by LiloBzH** [comment]
ok with : Linux proxmox 6.8.4-2-pve

after recomplication of Coral driver // gasket-dkms_1.0-18_all.deb

**Comment by dmandn** [comment]
Hi, I'm on Debian 12, tried with a kernel 6.8 install, plus proxmox 8 with kernel 6.8.x and no Debian 12 again, on kernal 6.1.0-21-amd64. I have followed your steps and from the basic checks, things seem ok on the host, but I cannot get the TPUs to work in/with anything.

When I perform a "dmesg | grep -i apex", I get the below:
# dmesg | grep -i apex
[   16.471161] apex 0000:08:00.0: enabling device (0000 -> 0002)
[   16.474447] apex 0000:08:00.0: Couldn't initialize interrupts: -22
[   16.476806] apex 0000:09:00.0: enabling device (0000 -> 0002)
[   16.480201] apex 0000:09:00.0: Couldn't initialize interrupts: -22
[   16.482306] apex 0000:0a:00.0: enabling device (0000 -> 0002)
[   16.488254] apex 0000:0a:00.0: Couldn't initialize interrupts: -22
[   21.504640] apex 0000:09:00.0: Apex performance not throttled due to temperature
[   21.504639] apex 0000:0a:00.0: Apex performance not throttled due to temperature
[   21.504657] apex 0000:08:00.0: Apex performance not throttled due to temperature
[  164.884046] apex 0000:0a:00.0: Couldn't reinit interrupts: -22
[  164.885596] apex 0000:08:00.0: Couldn't reinit interrupts: -22
[  164.889985] apex 0000:09:00.0: Couldn't reinit interrupts: -22
[  196.858032] apex 0000:0a:00.0: Couldn't reinit interrupts: -22
[  196.861839] apex 0000:08:00.0: Couldn't reinit interrupts: -22
[  196.866137] apex 0000:09:00.0: Couldn't reinit interrupts: -22
[  228.844407] apex 0000:0a:00.0: Couldn't reinit interrupts: -22
[  228.848057] apex 0000:08:00.0: Couldn't reinit interrupts: -22
[  228.852692] apex 0000:09:00.0: Couldn't reinit interrupts: -22
[  260.899907] apex 0000:0a:00.0: Couldn't reinit interrupts: -22
[  260.903764] apex 0000:08:00.0: Couldn't reinit interrupts: -22
[  260.908369] apex 0000:09:00.0: Couldn't reinit interrupts: -22

# ls -l /dev/apex*
crw-rw---- 1 root apex 120, 0 May 26 09:50 /dev/apex_0
crw-rw---- 1 root apex 120, 1 May 26 09:50 /dev/apex_1
crw-rw---- 1 root apex 120, 2 May 26 09:50 /dev/apex_2

# lspci  -nn | grep 089a
08:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
09:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
0a:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]

# lsmod | grep apex
apex                   28672  0
gasket                126976  1 apex

# apt list *apex*
Listing... Done
golang-github-apex-log-dev/stable 1.1.1-3 all

# apt list *gasket*
Listing... Error!
E: input:0-26: error: Expected pattern
   gasket-dkms_1.0-18_all.deb
   ^^^^^^^^^^^^^^^^^^^^^^^^^^

I have the same symptoms with this gasket-dkms build as I had with a previous one, except the permission denied errors are gone from the dmesg output now. Still unable to clear the "Couldn't initialise interrupts: -22" error, which I assume is part of the issue?

**Comment by dmandn** [comment]
Reinstalled fresh with debian 12, kernel 6.1.0-21-amd64 and is workign fine.

**Comment by hapklaar** [comment]
> Any future kernel updates should automatically include gasket-dkms after above steps.

@alienatedsec Using your guide the corals work fine for me in LXC on Proxmox, but I have to repeat after every kernel update. Any ideas why this is not automatic?

edit: just discovered I had everything but the 'proxmox-default-headers' package. Is this required for it to happen automatically perhaps?

**Comment by alienatedsec** [comment]
> Is this required for it to happen automatically perhaps?

@hapklaar I recon the missing package was the reason.

**Comment by Commod0re** [comment]
> @themana
> 
> ```
> sudo apt update
> sudo apt upgrade
> sudo apt install devscripts debhelper -y
> ```

this worked for me except I needed to also install `dh-dkms`

**Comment by ligistx** [comment]
> @themana
> 
> ```
> sudo apt update
> sudo apt upgrade
> sudo apt install devscripts debhelper -y
> ```
> 
> Then clone and the rest
> 
> > ```
> > ❯ git clone https://github.com/google/gasket-driver.git
> > Cloning into 'gasket-driver'...
> > ...
> > ❯ cd gasket-driver; debuild -us -uc -tc -b; cd ..
> > ...
> > dpkg-deb: building package 'gasket-dkms' in '../gasket-dkms_1.0-18_all.deb'.
> > ...
> > ❯ ls -l gasket-dkms*
> > -rw-r--r-- 1 dewet dewet 49000 Jan 17 13:17 gasket-dkms_1.0-18_all.deb
> > -rw-r--r-- 1 dewet dewet  1788 Jan 17 13:18 gasket-dkms_1.0-18_amd64.build
> > -rw-r--r-- 1 dewet dewet  5642 Jan 17 13:17 gasket-dkms_1.0-18_amd64.buildinfo
> > -rw-r--r-- 1 dewet dewet  1017 Jan 17 13:17 gasket-dkms_1.0-18_amd64.changes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can install that `.deb` on any systems that need to build the kernel module, and it will be rebuilt automatically with newer kernel packages being installed:
> > ```
> > ❯ sudo dpkg -i gasket-dkms_1.0-18_all.deb
> > ...
> > Setting up gasket-dkms (1.0-18) ...
> > ...
> > Building for 6.5.0-14-generic
> > Building initial module for 6.5.0-14-generic
> > ...
> > depmod...
> > Time: 0h:00m:10s
> > ❯ sudo modprobe apex
> > ❯ lsmod | grep apex
> > apex                   28672  0
> > gasket                135168  1 apex
> > ```

This worked great for Ubuntu 24.04.1 LTS for anyone else looking for this.

**Comment by viper2033** [comment]
I also have a problem, I hope someone can help me:
root@openmediavault:~# sudo dpkg -i gasket-dkms_1.0-18_all.deb
(Lese Datenbank ... 123732 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von gasket-dkms_1.0-18_all.deb ...
Deleting module gasket-1.0 completely from the DKMS tree.
Entpacken von gasket-dkms (1.0-18) über (1.0-18) ...
gasket-dkms (1.0-18) wird eingerichtet ...
Loading new gasket-1.0 DKMS files...
Deprecated feature: REMAKE_INITRD (/usr/src/gasket-1.0/dkms.conf)
Building for 6.12.12+bpo-amd64
Building initial module for 6.12.12+bpo-amd64
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/gasket/1.0/source/dkms.conf)
Error! Bad return status for module build on kernel: 6.12.12+bpo-amd64 (x86_64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: Fehler beim Bearbeiten des Paketes gasket-dkms (--install):
 »installiertes post-installation-Skript des Paketes gasket-dkms«-Unterprozess gab den Fehlerwert 10 zurück
Fehler traten auf beim Bearbeiten von:
 gasket-dkms

**Comment by whateverthatis** [comment]
I receive a similar error to the above:

root@pm:~# dpkg -i gasket-dkms_1.0-18_all.deb
(Reading database ... 101427 files and directories currently installed.)
Preparing to unpack gasket-dkms_1.0-18_all.deb ...
Deleting module gasket-1.0 completely from the DKMS tree.
Unpacking gasket-dkms (1.0-18) over (1.0-18) ...
Setting up gasket-dkms (1.0-18) ...
Loading new gasket-1.0 DKMS files...
Deprecated feature: REMAKE_INITRD (/usr/src/gasket-1.0/dkms.conf)
Building for 6.8.12-9-pve
Module build for kernel 6.8.12-9-pve was skipped since the
kernel headers for this kernel do not seem to be installed.

**Comment by alienatedsec** [comment]
> I receive a similar error to the above:
> 
> root@pm:~# dpkg -i gasket-dkms_1.0-18_all.deb
> (Reading database ... 101427 files and directories currently installed.)
> Preparing to unpack gasket-dkms_1.0-18_all.deb ...
> Deleting module gasket-1.0 completely from the DKMS tree.
> Unpacking gasket-dkms (1.0-18) over (1.0-18) ...
> Setting up gasket-dkms (1.0-18) ...
> Loading new gasket-1.0 DKMS files...
> Deprecated feature: REMAKE_INITRD (/usr/src/gasket-1.0/dkms.conf)
> Building for 6.8.12-9-pve
> Module build for kernel 6.8.12-9-pve was skipped since the
> kernel headers for this kernel do not seem to be installed.

@whateverthatis install kernel headers first

https://github.com/blakeblackshear/frigate/discussions/5448#discussioncomment-8855247

**Comment by eresonance** [comment]
Just for reference if anyone hits the same error as I did as it was a bit hard to find.

I'm on debian 13 (trixie) with kernel 6.12.38 and installing the resulting gasket-dkms deb fails:
```$ sudo dpkg -i gasket-dkms_1.0-18_all.deb
(Reading database ... 224767 files and directories currently installed.)
Preparing to unpack gasket-dkms_1.0-18_all.deb ...
Deleting module gasket/1.0 completely from the DKMS tree.
Unpacking gasket-dkms (1.0-18) over (1.0-18) ...
Setting up gasket-dkms (1.0-18) ...
Loading new gasket/1.0 DKMS files...
Deprecated feature: REMAKE_INITRD (/usr/src/gasket-1.0/dkms.conf)
Building for 6.12.38+deb13-amd64

Building initial module gasket/1.0 for 6.12.38+deb13-amd64
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/gasket/1.0/source/dkms.conf)
Sign command: /lib/modules/6.12.38+deb13-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
make -j4 KERNELRELEASE=6.12.38+deb13-amd64 -C /lib/modules/6.12.38+deb13-amd64/build M=/var/lib/dkms/gasket/1.0/build

Error! Bad return status for module build on kernel: 6.12.38+deb13-amd64 (x86_64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: error processing package gasket-dkms (--install):
 installed gasket-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 gasket-dkms
```

Looking at the build errors:
```DKMS (dkms-3.2.0) make.log for gasket/1.0 for kernel 6.12.38+deb13-amd64 (x86_64)
Sun 10 Aug 2025 11:44:24 AM EDT

Building module(s)
# command: make -j4 KERNELRELEASE=6.12.38+deb13-amd64 -C /lib/modules/6.12.38+deb13-amd64/build M=/var/lib/dkms/gasket/1.0/build
make: Entering directory '/usr/src/linux-headers-6.12.38+deb13-amd64'
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
/var/lib/dkms/gasket/1.0/build/gasket_core.c:1376:19: error: ‘no_llseek’ undeclared here (not in a function); did you mean ‘noop_llseek’?
 1376 |         .llseek = no_llseek,
      |                   ^~~~~~~~~
      |                   noop_llseek
make[2]: *** [/usr/src/linux-headers-6.12.38+deb13-common/scripts/Makefile.build:234: /var/lib/dkms/gasket/1.0/build/gasket_core.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-6.12.38+deb13-common/Makefile:1970: /var/lib/dkms/gasket/1.0/build] Error 2
make: *** [/usr/src/linux-headers-6.12.38+deb13-common/Makefile:236: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.12.38+deb13-amd64'

# exit code: 2
# elapsed time: 00:00:02
----------------------------------------------------------------
```

Looks like this was fixed in a fork:
https://github.com/google/gasket-driver/compare/main...sethyx:gasket-driver:main
As mentioned here:
https://github.com/google-coral/edgetpu/issues/905

Just grab this repo instead of the official one:
`git clone https://github.com/sethyx/gasket-driver.git`
With the repo from sethyx the dpkg command works and the module is installed correctly.

EDIT: Some more points.

Pin your package to prevent apt from updating it from the official google repo:
`nano /etc/apt/preferences.d/pin-gasket-dkms`

```
Package: gasket-dkms
Pin: origin "packages.cloud.google.com"
Pin-Priority: -1
```

And **disable secureboot**! You won't be able to load your self-built kernel modules if this is enabled.
