### ISSUE TITLE
DKMS gasket-dkms modules no longer build after upgrading kernel version > 5.7

### ISSUE THREAD

**Issue by kruftindustries** [google-coral/edgetpu#228]
`  MODPOST 2 modules
ERROR: modpost: "__stack_chk_guard" [/var/lib/dkms/gasket/1.0/build/apex.ko] undefined!
ERROR: modpost: "__stack_chk_guard" [/var/lib/dkms/gasket/1.0/build/gasket.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:99: __modpost] Error 1`

**Comment by Namburger** [comment]
@kruftindustries hello, could you provide a little more details or steps to reproduce?

**Comment by kruftindustries** [comment]
Sure. After upgrading the kernel (have not confirmed this is the cause of the problem but did reveal it) dkms fails to build gasket-dkms modules apex.ko and gasket.ko with the error message "__stack_chk_guard undefined!" this symbol seems to be related to the [stack smashing protector compiler feature](https://wiki.osdev.org/Stack_Smashing_Protector), I am not familiar with it.



System information:
**uname -a:** 
`Linux rockpi-4b 5.7.15-rockchip64 #20.08 SMP PREEMPT Mon Aug 17 00:26:28 CEST 2020 aarch64 GNU/Linux`

**gcc -v**
`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/8/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --disable-libphobos --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)`




**Steps to reproduce:**

**sudo apt upgrade:**
`...Unpacking linux-image-current-rockchip64 (20.08.7) over (20.08)...
Setting up linux-image-current-rockchip64 (20.08.7) ...
Error! Bad return status for module build on kernel: 5.8.13-rockchip64 (aarch64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
update-initramfs: Generating /boot/initrd.img-5.8.13-rockchip64`


**sudo apt install --reinstall gasket-dkms:**
`After this operation, 0 B of additional disk space will be used.
Setting up gasket-dkms (1.0-13) ...
Removing old gasket-1.0 DKMS files...

------------------------------
Deleting module version: 1.0
completely from the DKMS tree.
------------------------------
Done.
Loading new gasket-1.0 DKMS files...
Building for 5.7.15-rockchip64
Building initial module for 5.7.15-rockchip64
Error! Bad return status for module build on kernel: 5.7.15-rockchip64 (aarch64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: error processing package gasket-dkms (--configure):
 installed gasket-dkms package post-installation script subprocess returned erro           r exit status 10
Errors were encountered while processing:
 gasket-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**tail -n100 /var/lib/dkms/gasket/1.0/build/make.log for kernel 5.8.13**
`DKMS make.log for gasket-1.0 for kernel 5.8.13-rockchip64 (aarch64)
Mon 05 Oct 2020 02:50:01 PM UTC
make: Entering directory '/usr/src/linux-headers-5.8.13-rockchip64'
  AR      /var/lib/dkms/gasket/1.0/build/built-in.a
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
gcc: error: unrecognized command line option ‘-mbranch-protection=pac-ret+leaf’; did you mean ‘-fcf-protection=return’?
gcc: error: unrecognized command line option ‘-mbranch-protection=pac-ret+leaf’; did you mean ‘-fcf-protection=return’?
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_sysfs.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/apex_driver.o
gcc: error: unrecognized command line option ‘-mstack-protector-guard=sysreg’; did you mean ‘-fstack-protector-strong’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard=sysreg’; did you mean ‘-fstack-protector-strong’?
gcc: error: unrecognized command line option ‘-mbranch-protection=pac-ret+leaf’; did you mean ‘-fcf-protection=return’?
gcc: error: unrecognized command line option ‘-mbranch-protection=pac-ret+leaf’; did you mean ‘-fcf-protection=return’?
gcc: error: unrecognized command line option ‘-mbranch-protection=pac-ret+leaf’; did you mean ‘-fcf-protection=return’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-reg=sp_el0’; did you mean ‘-fstack-protector-all’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-reg=sp_el0’; did you mean ‘-fstack-protector-all’?
gcc: error: unrecognized command line option ‘-mbranch-protection=pac-ret+leaf’; did you mean ‘-fcf-protection=return’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard=sysreg’; did you mean ‘-fstack-protector-strong’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-offset=1192’; did you mean ‘-fstack-protector-strong’?
make[1]: *** [scripts/Makefile.build:281: /var/lib/dkms/gasket/1.0/build/gasket_core.o] Error 1
make[1]: *** Waiting for unfinished jobs....
gcc: error: unrecognized command line option ‘-mstack-protector-guard=sysreg’; did you mean ‘-fstack-protector-strong’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard=sysreg’; did you mean ‘-fstack-protector-strong’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-offset=1192’; did you mean ‘-fstack-protector-strong’?
make[1]: *** [scripts/Makefile.build:281: /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o] Error 1
gcc: error: unrecognized command line option ‘-mstack-protector-guard=sysreg’; did you mean ‘-fstack-protector-strong’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-reg=sp_el0’; did you mean ‘-fstack-protector-all’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-reg=sp_el0’; did you mean ‘-fstack-protector-all’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-reg=sp_el0’; did you mean ‘-fstack-protector-all’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-reg=sp_el0’; did you mean ‘-fstack-protector-all’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-offset=1192’; did you mean ‘-fstack-protector-strong’?
make[1]: *** [scripts/Makefile.build:281: /var/lib/dkms/gasket/1.0/build/gasket_sysfs.o] Error 1
gcc: error: unrecognized command line option ‘-mstack-protector-guard-offset=1192’; did you mean ‘-fstack-protector-strong’?
make[1]: *** [scripts/Makefile.build:281: /var/lib/dkms/gasket/1.0/build/apex_driver.o] Error 1
gcc: error: unrecognized command line option ‘-mstack-protector-guard-offset=1192’; did you mean ‘-fstack-protector-strong’?
gcc: error: unrecognized command line option ‘-mstack-protector-guard-offset=1192’; did you mean ‘-fstack-protector-strong’?
make[1]: *** [scripts/Makefile.build:281: /var/lib/dkms/gasket/1.0/build/gasket_page_table.o] Error 1
make[1]: *** [scripts/Makefile.build:281: /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o] Error 1
make: *** [Makefile:1752: /var/lib/dkms/gasket/1.0/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.8.13-rockchip64'`

**tail -n100 /var/lib/dkms/gasket/1.0/build/make.log for kernel 5.7.15**
`DKMS make.log for gasket-1.0 for kernel 5.7.15-rockchip64 (aarch64)
Mon 05 Oct 2020 10:22:15 AM UTC
make: Entering directory '/usr/src/linux-headers-5.7.15-rockchip64'
  AR      /var/lib/dkms/gasket/1.0/build/built-in.a
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_sysfs.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/apex_driver.o
  LD [M]  /var/lib/dkms/gasket/1.0/build/apex.o
  LD [M]  /var/lib/dkms/gasket/1.0/build/gasket.o
  MODPOST 2 modules
ERROR: modpost: "__stack_chk_guard" [/var/lib/dkms/gasket/1.0/build/apex.ko] und                                                                                                                                                                                                                                             efined!
ERROR: modpost: "__stack_chk_guard" [/var/lib/dkms/gasket/1.0/build/gasket.ko] u                                                                                                                                                                                                                                             ndefined!
make[1]: *** [scripts/Makefile.modpost:99: __modpost] Error 1
make: *** [Makefile:1645: modules] Error 2
make: Leaving directory '/usr/src/linux-headers-5.7.15-rockchip64'`



It might be possible to cd to /var/lib/dkms/gasket/1.0/build/ and manually make gasket-objs and gasket-objs with flag -fno-stack-protector ? I'm thinking eventually someone else will run into this problem so maybe there is a better solution.

**Comment by Namburger** [comment]
Hi @kruftindustries Ahh, I see, I believe this is due to a missing kernel configs for the stackguard. 
I'm not sure how to turn this on for the Rockchip, but I suggest checking to see if these configs are turned on:
```
➜  ~ cat /boot/config-5.4.0-48-generic | grep STACKPROTECTOR 
CONFIG_CC_HAS_SANE_STACKPROTECTOR=y
CONFIG_HAVE_STACKPROTECTOR=y
CONFIG_CC_HAS_STACKPROTECTOR_NONE=y
CONFIG_STACKPROTECTOR=y
CONFIG_STACKPROTECTOR_STRONG=y
```

if not I suggest you change the defconfig to turn it on and recompiling the kernel

**Comment by kruftindustries** [comment]
Configs look correct:

**cat /boot/config-5.8.13-rockchip64 | grep STACKPROTECTOR**

`CONFIG_CC_HAVE_STACKPROTECTOR_SYSREG=y
CONFIG_STACKPROTECTOR_PER_TASK=y
CONFIG_HAVE_STACKPROTECTOR=y
CONFIG_CC_HAS_STACKPROTECTOR_NONE=y
CONFIG_STACKPROTECTOR=y
CONFIG_STACKPROTECTOR_STRONG=y`

**Comment by kruftindustries** [comment]
@Namburger any further suggestions?

**Comment by Namburger** [comment]
@kruftindustries I see, could you try compiling the kernel again with out pcie source code in the kernel tree?
It is hosted here: https://coral.googlesource.com/linux-imx/+/refs/heads/dkms/drivers/staging/gasket

**Comment by jbergler** [comment]
This seems like it might have a similar root cause to the problem I've been trying to debug in https://github.com/openzfs/zfs/issues/10985

Out of curiosity, can you check the gcc version that the kernel was built with vs the what toolchain you're running.
```
gcc --version
cat /proc/version
```

**Comment by kruftindustries** [comment]
**gcc --version**
```gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.```

**cat /proc/version**
```Linux version 5.8.13-rockchip64 (root@xeon) (aarch64-none-linux-gnu-gcc (GNU Toolchain for the A-profile Architecture 9.2-2019.12 (arm-9.10)) 9.2.1 20191025, GNU ld (GNU Toolchain for the A-profile Architecture 9.2-2019.12 (arm-9.10)) 2.33.1.20191209) #20.08.7 SMP PREEMPT Fri Oct 2 10:36:32 CEST 2020```

**Comment by Namburger** [comment]
@jbergler thanks for your inputs, 
@kruftindustries it may be worth trying to build this again after upgrading gcc to 9.2.1

**Comment by kruftindustries** [comment]
I noticed earlier my kernel source also has Apex and Gasket in the staging (Device Drivers > Staging drivers > Gasket devices). I will try building on the development machine after enabling with menuconfig.

**Comment by kruftindustries** [comment]
The build was successful and looks like there were no compilation errors. I ended up using the armbian tool to cross compile with gcc version 9.3.0(-17ubuntu1~20.04), enabled apex and gasket in menuconfig and upon booting the board I have /dev/apex_0

The new image has gcc version 9.3.0(-12ubuntu2) so I probably couldn't reproduce this issue without doing buildroot, however the reported issue with building seems to be resolved.

Thanks guys!

**Comment by Namburger** [comment]
@kruftindustries , but def thanks @jbergler for inputs!
