### ISSUE TITLE
Errors when retraining EfficientDet-Lite

### ISSUE THREAD

**Issue by dyoo-dev** [google-coral/edgetpu#444]
Hello, 

I am retraining EfficientDet-Lite models using the Jupyter notebook you shared (https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_efficientdet_model_maker_tf2.ipynb)

When I used Lite2 spec, I was able to get the TPU model successfully. But when I used Lite4 spec, I got errors from the following commands. 

1. evaluate a tflite model
This is the command 
```
model.evaluate_tflite('efficientdet-lite-model.tflite', test_data)
```
This is the error message I've got. 
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-25-5af85673802f> in <module>()
----> 1 model.evaluate_tflite('efficientdet-lite-model.tflite', test_data)

8 frames
/usr/local/lib/python3.7/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: required broadcastable shapes [Op:Mul]
```
2. Edge TPU compiler error
Also, I got this error message when I compiled the model using edgetpu_compiler
```
Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
```

Any thought?

**Comment by hjonnala** [comment]
Hi, the issue (InvalidArgumentError: required broadcastable shapes [Op:Mul]) is coming form tensorflow tflite model itself. We are not experts in solving these issues. Please check with tensor flow lite team regarding this.

**Comment by dyoo-dev** [comment]
Thank you @hjonnala. 

How about the compiler error?

**Comment by hjonnala** [comment]
Compilation is recommended only after successful inference with CPU tflite model. Please get back to us if there are no issues with CPU tflite model.

**Comment by hjonnala** [comment]
Please reopen the issue if there are no issues with CPU tflite model and the compiler is not able to compile the model.

**Comment by hjonnala** [comment]
@dyoo-dev to resolve the compilation failure due to large activation tensors in model try with -a -d flags and **wait** for the full execution of command. To know more about the details of flags please refer to this resource: https://coral.ai/docs/edgetpu/compiler/#usage

`!edgetpu_compiler -s -a -d -k 10 efficientdet-lite-salads.tflite`

**Comment by dyoo-dev** [comment]
I don't have issues with CPU tflite model. 

I used the -a -d flags but I still have the compiler issue. 

```
Edge TPU Compiler version 16.0.384591198
Searching for valid delegate with step 10
Try to compile segment with 322 ops
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 312 ops
Intermediate tensors: Reshape_5,Sigmoid1,Relu6_12;box-0-bn-7/FusedBatchNormV3;box_net/box-0/bias;box-0/BiasAdd_4;class_net/class-predict/separable_conv2d_4/depthwise;box-0/separable_conv2d_41,Reshape_3,Reshape_1,Reshape_7
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 302 ops
Intermediate tensors: Relu6_13;class-1-bn-7/FusedBatchNormV3;class_net/class-1/bias;class-1/BiasAdd_4;class_net/class-predict/separable_conv2d_4/depthwise;class-1/separable_conv2d_41,Reshape_4,Reshape,Reshape_7,Reshape_3,cell_3/fnode7/op_after_combine12/bn/FusedBatchNormV3;fpn_cells/cell_3/fnode7/op_after_combine12/conv/bias;cell_3/fnode7/op_after_combine12/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_3/fnode7/op_after_combine12/conv/separable_conv2d,Reshape_6,Reshape_2,Reshape_5,Reshape_1
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 292 ops
Intermediate tensors: cell_2/fnode7/op_after_combine12/bn/FusedBatchNormV3;fpn_cells/cell_2/fnode7/op_after_combine12/conv/bias;cell_2/fnode7/op_after_combine12/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_2/fnode7/op_after_combine12/conv/separable_conv2d,Reshape_1,Reshape,Reshape_4,cell_3/fnode6/op_after_combine11/bn/FusedBatchNormV3;fpn_cells/cell_3/fnode6/op_after_combine11/conv/bias;cell_3/fnode6/op_after_combine11/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_3/fnode6/op_after_combine11/conv/separable_conv2d,box_net/box-predict/separable_conv2d_3/depthwise,Reshape_3,Reshape_6,Reshape_2,Reshape_5
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
Try to compile segment with 282 ops
Intermediate tensors: cell_2/fnode7/op_after_combine12/bn/FusedBatchNormV3;fpn_cells/cell_2/fnode7/op_after_combine12/conv/bias;cell_2/fnode7/op_after_combine12/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_2/fnode7/op_after_combine12/conv/separable_conv2d,Reshape_1,Reshape,Reshape_4,cell_3/fnode6/op_after_combine11/bn/FusedBatchNormV3;fpn_cells/cell_3/fnode6/op_after_combine11/conv/bias;cell_3/fnode6/op_after_combine11/conv/BiasAdd;class_net/class-predict/separable_conv2d_4/depthwise;cell_3/fnode6/op_after_combine11/conv/separable_conv2d,Relu6_11;class-2-bn-6/FusedBatchNormV3;class_net/class-2/bias;class-2/BiasAdd_3;class_net/class-predict/separable_conv2d_4/depthwise;class-2/separable_conv2d_31,Reshape_3,Reshape_2,Reshape_5
Started a compilation timeout timer of 180 seconds.
ERROR: Restored original execution plan after delegate application failure.
Compilation failed: Compilation failed due to large activation tensors in model.
Compilation child process completed within timeout period.
Compilation failed! 
...
```

**Comment by hjonnala** [comment]
@dyoo-dev please share your cpu tflite model.

**Comment by dyoo-dev** [comment]
@hjonnala I attached the model here. Thanks. 

[model.zip](https://github.com/google-coral/edgetpu/files/7121989/model.zip)

**Comment by hjonnala** [comment]
@dyoo-dev I am not able compile the model with new compiler, but able to compile with `Edge TPU Compiler version 15.0.340273435`. Please check attachment for edgetpu file.

[edgetpu_444.tar.gz](https://github.com/google-coral/edgetpu/files/7244936/edgetpu_444.tar.gz)

**Comment by hjonnala** [comment]
@dyoo-dev  please try the command below, you would be able to compile the model.

`!edgetpu_compiler -s -d  efficientdet-lite.tflite`
