### ISSUE TITLE
gasket-dkms installation fails on debian testing (Trixie)

### ISSUE THREAD

**Issue by pgenera** [google-coral/edgetpu#785]
### Description

Installing gasket fails to compile on Debian testing at the moment. This has appeared with the 6.4 kernel packages, although I think there were gcc updates in there too.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Linux

### Coral Device

Mini PCIe

### Programming Language

C++

### Relevant Log Output

```shell
$ less  /var/lib/dkms/gasket/1.0/build/make.log 
DKMS make.log for gasket-1.0 for kernel 6.4.0-1-amd64 (x86_64)
Thu Aug 10 08:03:01 AM EDT 2023
make: Entering directory '/usr/src/linux-headers-6.4.0-1-amd64'
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
/var/lib/dkms/gasket/1.0/build/gasket_core.c: In function ‘gasket_register_device’:
/var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:41: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1841 |                 class_create(driver_desc->module, driver_desc->name);
      |                              ~~~~~~~~~~~^~~~~~~~
      |                                         |
      |                                         struct module *
In file included from /usr/src/linux-headers-6.4.0-1-common/include/linux/device.h:31,
                 from /usr/src/linux-headers-6.4.0-1-common/include/linux/cdev.h:8,
                 from /var/lib/dkms/gasket/1.0/build/gasket_core.h:11,
                 from /var/lib/dkms/gasket/1.0/build/gasket_core.c:12:
/usr/src/linux-headers-6.4.0-1-common/include/linux/device/class.h:230:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
  230 | struct class * __must_check class_create(const char *name);
      |                                          ~~~~~~~~~~~~^~~~
/var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:17: error: too many arguments to function ‘class_create’
 1841 |                 class_create(driver_desc->module, driver_desc->name);
      |                 ^~~~~~~~~~~~
/usr/src/linux-headers-6.4.0-1-common/include/linux/device/class.h:230:29: note: declared here
  230 | struct class * __must_check class_create(const char *name);
      |                             ^~~~~~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [/usr/src/linux-headers-6.4.0-1-common/scripts/Makefile.build:257: /var/lib/dkms/gasket/1.0/build/gasket_core.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [/usr/src/linux-headers-6.4.0-1-common/Makefile:2051: /var/lib/dkms/gasket/1.0/build] Error 2
make: Leaving directory '/usr/src/linux-headers-6.4.0-1-amd64'

$ cc --version
cc (Debian 13.2.0-1) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ dpkg -l gcc
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  gcc            4:13.1.0-4   amd64        GNU C compiler
```
</details>

**Comment by bawachhe** [comment]
dupes #695

Issue has to do with kernel 6.4 making the relevant breaking change to the function signature (number of params) of `class_create`

**Comment by Ofloo** [comment]
I can confirm i'm having the same issue with rpi5
root@crsn5:/home/ofloo# uname -a
Linux crsn5 6.12.47+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.12.47-1+rpt1 (2025-09-16) aarch64 GNU/Linux

```
Preparing to unpack .../gasket-dkms_1.0-18_all.deb ...
Unpacking gasket-dkms (1.0-18) ...
Setting up gasket-dkms (1.0-18) ...
Loading new gasket/1.0 DKMS files...
Deprecated feature: REMAKE_INITRD (/usr/src/gasket-1.0/dkms.conf)
Building for 6.12.47+rpt-rpi-2712, 6.12.47+rpt-rpi-v8 and 6.12.57+deb13-arm64

Building initial module gasket/1.0 for 6.12.47+rpt-rpi-2712
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/gasket/1.0/source/dkms.conf)
The kernel is built without module signing facility, modules won't be signed

Building module(s)...(bad exit status: 2)
Failed command:
make -j4 KERNELRELEASE=6.12.47+rpt-rpi-2712 -C /lib/modules/6.12.47+rpt-rpi-2712/build M=/var/lib/dkms/gasket/1.0/build

Error! Bad return status for module build on kernel: 6.12.47+rpt-rpi-2712 (aarch64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: error processing package gasket-dkms (--configure):
 installed gasket-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 gasket-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Buildlog:

```
DKMS (dkms-3.2.2) make.log for gasket/1.0 for kernel 6.12.47+rpt-rpi-2712 (aarch64)
Fri Dec 26 18:59:44 GMT 2025

Building module(s)
# command: make -j4 KERNELRELEASE=6.12.47+rpt-rpi-2712 -C /lib/modules/6.12.47+rpt-rpi-2712/build M=/var/lib/dkms/gasket/1.0/build
make: Entering directory '/usr/src/linux-headers-6.12.47+rpt-rpi-2712'
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_core.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_ioctl.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o
  CC [M]  /var/lib/dkms/gasket/1.0/build/gasket_page_table.o
/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c: In function <E2><80><98>gasket_handle_interrupt<E2><80><99>:
/var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:161:17: error: too many arguments to function <E2><80><98>eventfd_signal<E2><80><99>
  161 |                 eventfd_signal(ctx, 1);
      |                 ^~~~~~~~~~~~~~
In file included from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.h:11,
                 from /var/lib/dkms/gasket/1.0/build/gasket_interrupt.c:4:
/usr/src/linux-headers-6.12.47+rpt-common-rpi/include/linux/eventfd.h:87:20: note: declared here
   87 | static inline void eventfd_signal(struct eventfd_ctx *ctx)
      |                    ^~~~~~~~~~~~~~
make[2]: *** [/usr/src/linux-headers-6.12.47+rpt-common-rpi/scripts/Makefile.build:249: /var/lib/dkms/gasket/1.0/build/gasket_interrupt.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/gasket/1.0/build/gasket_core.c:1375:19: error: <E2><80><98>no_llseek<E2><80><99> undeclared here (not in a function); did you mean <E2><80><98>noop_llseek<E2><80><99>?
 1375 |         .llseek = no_llseek,
      |                   ^~~~~~~~~
      |                   noop_llseek
/var/lib/dkms/gasket/1.0/build/gasket_core.c: In function <E2><80><98>gasket_register_device<E2><80><99>:
/var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:41: error: passing argument 1 of <E2><80><98>class_create<E2><80><99> from incompatible pointer type [-Wincompatible-pointer-types]
 1841 |                 class_create(driver_desc->module, driver_desc->name);
      |                              ~~~~~~~~~~~^~~~~~~~
      |                                         |
      |                                         struct module *
In file included from /usr/src/linux-headers-6.12.47+rpt-common-rpi/include/linux/device.h:30,
                 from /usr/src/linux-headers-6.12.47+rpt-common-rpi/include/linux/cdev.h:8,
                 from /var/lib/dkms/gasket/1.0/build/gasket_core.h:11,
                 from /var/lib/dkms/gasket/1.0/build/gasket_core.c:12:
/usr/src/linux-headers-6.12.47+rpt-common-rpi/include/linux/device/class.h:228:54: note: expected <E2><80><98>const char *<E2><80><99> but argument is of type <E2><80><98>struct module *<E2><80><99>
  228 | struct class * __must_check class_create(const char *name);
      |                                          ~~~~~~~~~~~~^~~~
/var/lib/dkms/gasket/1.0/build/gasket_core.c:1841:17: error: too many arguments to function <E2><80><98>class_create<E2><80><99>
 1841 |                 class_create(driver_desc->module, driver_desc->name);
      |                 ^~~~~~~~~~~~
/usr/src/linux-headers-6.12.47+rpt-common-rpi/include/linux/device/class.h:228:29: note: declared here
  228 | struct class * __must_check class_create(const char *name);
      |                             ^~~~~~~~~~~~
make[2]: *** [/usr/src/linux-headers-6.12.47+rpt-common-rpi/scripts/Makefile.build:249: /var/lib/dkms/gasket/1.0/build/gasket_core.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.12.47+rpt-common-rpi/Makefile:1970: /var/lib/dkms/gasket/1.0/build] Error 2
make: *** [/usr/src/linux-headers-6.12.47+rpt-common-rpi/Makefile:236: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.12.47+rpt-rpi-2712'

# exit code: 2
# elapsed time: 00:00:01
----------------------------------------------------------------
```
