### ISSUE TITLE
Gasket-dkms install error on 6.14.8-2-pve

### ISSUE THREAD

**Issue by xsleepejelly** [google-coral/edgetpu#905]
### Description

Installing on Proxmox VE
pve-manager/9.0.3/025864202ebb6109 (running kernel: 6.14.8-2-pve)

Running apt install gasket-dkms runs into an error

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Linux

### Coral Device

M.2 Accelerator B+M

### Relevant Log Output

```shell
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0sudo: apt-key: command not found
100  1022  100  1022    0     0   5132      0 --:--:-- --:--:-- --:--:--  5135
curl: Failed writing body

----------------------------------------------------------

Preparing to unpack .../gasket-dkms_1.0-18_all.deb ...
Unpacking gasket-dkms (1.0-18) ...
Setting up gasket-dkms (1.0-18) ...
Loading new gasket/1.0 DKMS files...
Deprecated feature: REMAKE_INITRD (/usr/src/gasket-1.0/dkms.conf)
Building for 6.14.8-2-pve

Building initial module gasket/1.0 for 6.14.8-2-pve
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/gasket/1.0/source/dkms.conf)
Sign command: /lib/modules/6.14.8-2-pve/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
make -j20 KERNELRELEASE=6.14.8-2-pve -C /lib/modules/6.14.8-2-pve/build M=/var/lib/dkms/gasket/1.0/build

Error! Bad return status for module build on kernel: 6.14.8-2-pve (x86_64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: error processing package gasket-dkms (--configure):
 installed gasket-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 gasket-dkms
Error: Sub-process /usr/bin/dpkg returned an error code (1)

------------------------------------------------------------------

DKMS (dkms-3.2.0) make.log for gasket/1.0 for kernel 6.14.8-2-pve (x86_64)
Sat Aug  9 12:32:15 AM CDT 2025

Building module(s)
# command: make -j20 KERNELRELEASE=6.14.8-2-pve -C /lib/modules/6.14.8-2-pve/build M=/var/lib/dkms/gasket/1.0/build
make: Entering directory '/usr/src/linux-headers-6.14.8-2-pve'
make[1]: Entering directory '/var/lib/dkms/gasket/1.0/build'
  CC [M]  gasket_core.o
  CC [M]  gasket_ioctl.o
  CC [M]  gasket_interrupt.o
  CC [M]  gasket_page_table.o
  CC [M]  gasket_sysfs.o
  CC [M]  apex_driver.o
gasket_interrupt.c: In function ‘gasket_handle_interrupt’:
gasket_interrupt.c:161:17: error: too many arguments to function ‘eventfd_signal’
  161 |                 eventfd_signal(ctx, 1);
      |                 ^~~~~~~~~~~~~~
In file included from gasket_interrupt.h:11,
                 from gasket_interrupt.c:4:
/usr/src/linux-headers-6.14.8-2-pve/include/linux/eventfd.h:87:20: note: declared here
   87 | static inline void eventfd_signal(struct eventfd_ctx *ctx)
      |                    ^~~~~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-6.14.8-2-pve/scripts/Makefile.build:207: gasket_interrupt.o] Error 1
make[3]: *** Waiting for unfinished jobs....
gasket_core.c:1375:19: error: ‘no_llseek’ undeclared here (not in a function); did you mean ‘noop_llseek’?
 1375 |         .llseek = no_llseek,
      |                   ^~~~~~~~~
      |                   noop_llseek
In file included from /usr/src/linux-headers-6.14.8-2-pve/include/linux/module.h:22,
                 from /usr/src/linux-headers-6.14.8-2-pve/include/linux/device/driver.h:21,
                 from /usr/src/linux-headers-6.14.8-2-pve/include/linux/device.h:32,
                 from /usr/src/linux-headers-6.14.8-2-pve/include/linux/pci.h:37,
                 from gasket_page_table.h:15,
                 from gasket_page_table.c:42:
gasket_page_table.c:57:18: error: expected ‘,’ or ‘;’ before ‘DMA_BUF’
   57 | MODULE_IMPORT_NS(DMA_BUF);
      |                  ^~~~~~~
/usr/src/linux-headers-6.14.8-2-pve/include/linux/moduleparam.h:26:61: note: in definition of macro ‘__MODULE_INFO’
   26 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
      |                                                             ^~~~
/usr/src/linux-headers-6.14.8-2-pve/include/linux/module.h:301:33: note: in expansion of macro ‘MODULE_INFO’
  301 | #define MODULE_IMPORT_NS(ns)    MODULE_INFO(import_ns, ns)
      |                                 ^~~~~~~~~~~
gasket_page_table.c:57:1: note: in expansion of macro ‘MODULE_IMPORT_NS’
   57 | MODULE_IMPORT_NS(DMA_BUF);
      | ^~~~~~~~~~~~~~~~
gasket_core.c: In function ‘gasket_register_device’:
gasket_core.c:1841:41: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Wincompatible-pointer-types]
 1841 |                 class_create(driver_desc->module, driver_desc->name);
      |                              ~~~~~~~~~~~^~~~~~~~
      |                                         |
      |                                         struct module *
In file included from /usr/src/linux-headers-6.14.8-2-pve/include/linux/device.h:31,
                 from /usr/src/linux-headers-6.14.8-2-pve/include/linux/cdev.h:8,
                 from gasket_core.h:11,
                 from gasket_core.c:12:
/usr/src/linux-headers-6.14.8-2-pve/include/linux/device/class.h:226:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
  226 | struct class * __must_check class_create(const char *name);
      |                                          ~~~~~~~~~~~~^~~~
gasket_core.c:1841:17: error: too many arguments to function ‘class_create’
 1841 |                 class_create(driver_desc->module, driver_desc->name);
      |                 ^~~~~~~~~~~~
/usr/src/linux-headers-6.14.8-2-pve/include/linux/device/class.h:226:29: note: declared here
  226 | struct class * __must_check class_create(const char *name);
      |                             ^~~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-6.14.8-2-pve/scripts/Makefile.build:207: gasket_core.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.14.8-2-pve/scripts/Makefile.build:207: gasket_page_table.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.14.8-2-pve/Makefile:2001: .] Error 2
make[1]: *** [/usr/src/linux-headers-6.14.8-2-pve/Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/gasket/1.0/build'
make: *** [Makefile:251: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.14.8-2-pve'

# exit code: 2
```</details>

**Comment by xsleepejelly** [comment]
Decided to apt remove devscripts dh-dkms dkms pve-headers-$(uname -r)
and apt autoremove
reboot
followed steps using the fork and instructions below

https://github.com/sethyx/gasket-driver.git
https://forum.proxmox.com/threads/pcie-google-coral-install-instructions.143187/#post-787385

installed and working correctly
